"""
Django settings for bus project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATES_DIR = os.path.join(BASE_DIR, 'templates')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w+jzfincsmp#i^9ijppj7a*a&ryrhn4@a&om%h_%k37=5m_n0j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ticket.apps.TicketConfig',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bus.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATES_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bus.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = ['static/']

STATIC_ROOT = 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# SSLCOMMERZ Settings
STORE_ID = 'testbox'  # Your SSLCOMMERZ Store ID
STORE_PASSWORD = 'qwerty'  # Your SSLCOMMERZ Store Password
SSLCOMMERZ_PAYMENT_URL = 'https://sandbox.sslcommerz.com/gwprocess/v4/api.php'  # Sandbox URL
SUCCESS_URL = 'payment-success/'
FAIL_URL = 'payment-fail/'
CANCEL_URL = 'payment-cancel/'
IPNURL = 'payment-ipn/'

# For development/testing
SSLCOMMERZ_IS_SANDBOX = True

# Configure logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'ticket': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

# Auth settings
AUTH_USER_MODEL = 'ticket.User'
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

JAZZMIN_SETTINGS = {
    "site_title": "BusTicketPro Admin",
    "site_header": "BusTicketPro Admin",
    "site_brand": "BusTicketPro",
    "site_logo": "img/logo.png",  # Place your logo at static/img/logo.png
    "site_icon": "img/favicon.ico",  # Place your favicon at static/img/favicon.ico
    "welcome_sign": "Welcome to BusTicketPro Admin",
    "copyright": "BusTicketPro",
    "primary_color": "#2563eb",  # Blue-600
    "accent": "#38bdf8",         # Sky-400
    "navbar": "#1e293b",         # Slate-800
    "no_navbar_border": True,
    "user_avatar": None,
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["ticket", "auth"],
    "icons": {
        "ticket.bus": "fas fa-bus",
        "ticket.route": "fas fa-route",
        "ticket.schedule": "fas fa-calendar-alt",
        "ticket.booking": "fas fa-ticket-alt",
        "ticket.ticket": "fas fa-receipt",
        "auth.user": "fas fa-user",
    },
    
    "custom_css": None,  # Place your custom CSS at static/css/custom_admin.css
    "custom_js": None,
}

# Email settings for development
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'mdfahmidbinmostafa@gmail.com'  # Replace with your Gmail address
# You need to use an App Password instead of your regular password
# Generate one at https://myaccount.google.com/ → Security → App passwords (after enabling 2-Step Verification)
EMAIL_HOST_PASSWORD = 'glffppadhqigbvei'  # Replace with your Gmail app password
DEFAULT_FROM_EMAIL = 'BusTicketPro <mdfahmidbinmostafa@gmail.com>'  # Replace with your Gmail address
